/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    fontFamily: {
      sans: ["ui-sans-serif", "system-ui"],
      serif: ["ui-serif", "Georgia"],
      mono: ["ui-monospace", "SFMono-Regular"],
    },
    extend: {
      colors: {
        primary: "#5CB85C",
        disabled: "#757575",
        "page-background": "#212121",
        "editor-background": "#2E2E2E",
        "editor-text": "#F5F5F5",
        "header-text": "#E0E0E0",
        "toolbar-background": "#424242",
        "toolbar-hover": "#212121",
        "toolbar-text": "#F5F5F5",
        "toolbar-disabled": "#757575",
        "toolbar-clicked": "#161c18",
        "toolbar-danger": "#D9534F",
        "toolbar-success": "#5CB85C",
        "toolbar-unsaved": "#FFC107",
        "floating-input-border": "#F5F5F5",
        "floating-input-border-focused": "#5CB85C",
        "floating-intput-label-text": "#F5F5F5",
        "floating-input-label-background": "#424242",
        "floating-input-label-focused": "#5CB85C",
        "code-background": "#212121",
        "code-highlight-atrule": "#FF6E87",
        "code-highlight-attr": "#96DB76",
        "code-highlight-boolean": "#C993FF",
        "code-highlight-builtin": "#96DB76",
        "code-highlight-cdata": "#7D7A70",
        "code-highlight-char": "#FDF57C",
        "code-highlight-class": "#96DB76",
        "code-highlight-class-name": "#96DB76",
        "code-highlight-comment": "#7D7A70",
        "code-highlight-constant": "#6BB7FF",
        "code-highlight-deleted": "#FF6E87",
        "code-highlight-doctype": "#F5F5F5",
        "code-highlight-entity": "#F5F5F5",
        "code-highlight-function": "#96DB76",
        "code-highlight-important": "#FFD457",
        "code-highlight-inserted": "#96DB76",
        "code-highlight-keyword": "#FF6E87",
        "code-highlight-namespace": "#FF6E87",
        "code-highlight-number": "#C993FF",
        "code-highlight-operator": "#FF6E87",
        "code-highlight-prolog": "#7D7A70",
        "code-highlight-property": "#96DB76",
        "code-highlight-punctuation": "#F5F5F5",
        "code-highlight-regex": "#FDF57C",
        "code-highlight-selector": "#FF6E87",
        "code-highlight-string": "#FDF57C",
        "code-highlight-symbol": "#FF6E87",
        "code-highlight-tag": "#FF6E87",
        "code-highlight-url": "#6BB7FF",
        "code-highlight-variable": "#F5F5F5",
        link: "#8ab4f8",
      },
    },
  },
  plugins: [],
};
