export const EditorTheme = {
  ltr: "text-left",
  rtl: "text-right",
  paragraph: "mb-4 last:mb-0",
  text: {
    bold: "font-bold",
    italic: "italic",
    strikethrough: "line-through",
    underline: "underline",
    underlineStrikethrough: "custom-underline-strikethrough",
  },
  quote: "border-l-4 my-4 text-lg ml-4 pl-4",
  heading: {
    h1: "text-3xl mb-4",
    h2: "text-xl mb-4",
    h3: "text-lg mb-4",
  },
  list: {
    listitem: "mb-2",
    nested: {
      listitem: "list-none",
    },
    olDepth: [
      "list-inside list-decimal",
      "pl-4 list-inside list-decimal",
      "pl-8 list-inside list-decimal",
      "pl-12 list-inside list-decimal",
      "pl-16 list-inside list-decimal",
    ],
    ul: "list-disc ml-4",
  },
  code: "block leading-6 bg-gray-800 py-2 font-mono block pl-10 relative whitespace-pre-wrap before:py-2 before:text-disabled before:content-[attr(data-gutter)] before:absolute before:top-0 before:left-0 before:border-disabled before:border-r before:pr-2 before:pl-4 mb-2",
  codeHighlight: {
    atrule: "text-code-highlight-atrule",
    attr: "text-code-highlight-attr",
    boolean: "text-code-highlight-boolean",
    builtin: "text-code-highlight-builtin",
    cdata: "text-code-highlight-cdata",
    char: "text-code-highlight-char",
    class: "text-code-highlight-class",
    "class-name": "text-code-highlight-class-name",
    comment: "text-code-highlight-comment",
    constant: "text-code-highlight-constant",
    deleted: "text-code-highlight-deleted",
    doctype: "text-code-highlight-doctype",
    entity: "text-code-highlight-entity",
    function: "text-code-highlight-function",
    important: "text-code-highlight-important",
    inserted: "text-code-highlight-inserted",
    keyword: "text-code-highlight-keyword",
    namespace: "text-code-highlight-namespace",
    number: "text-code-highlight-number",
    operator: "text-code-highlight-operator",
    prolog: "text-code-highlight-prolog",
    property: "text-code-highlight-property",
    punctuation: "text-code-highlight-punctuation",
    regex: "text-code-highlight-regex",
    selector: "text-code-highlight-selector",
    string: "text-code-highlight-string",
    symbol: "text-code-highlight-symbol",
    tag: "text-code-highlight-tag",
    url: "text-code-highlight-url",
    variable: "text-code-highlight-variable",
  },
  link: "text-blue-500",
};
